name: LeastPrivilegeManagement
version: '${project.version}'
main: me.karltroid.leastprivilegemanagement.LeastPrivilegeManagement
api-version: '1.20'
commands:
  target:
    description: Puts admin in spectating mode and optionally teleports to target player
    usage: /target <player>
    permission: leastprivilegemanagement.admin
    aliases: [ admin ]
  reveal:
    description: Puts admin in spectating mode in adventure mode to show themselves to the target player
    usage: /reveal
    permission: leastprivilegemanagement.admin
    aliases: [ show ]