name: LeastPrivilegeManagement
version: '1.0'
main: me.karltroid.leastprivilegemanagement.LeastPrivilegeManagement
api-version: '1.20'
commands:
  target:
    description: Puts admin in spectating mode and optionally teleports to target player
    usage: /target <player>
    permission: leastprivilegemanagement.admin
    aliases: [ admin, tp, teleport, spec, spectate, gmsp ]
  reveal:
    description: Puts admin in spectating mode in survival mode to show themselves to the target player
    usage: /reveal
    permission: leastprivilegemanagement.admin
    aliases: [ show, gms, survival, gm0 ]
  back:
    description: Teleports an admin to their previous teleported location
    usage: /back
    permission: leastprivilegemanagement.admin
  forward:
    description: Teleports an admin back to where they were before their previous /back
    usage: /forward
    permission: leastprivilegemanagement.admin
  freeze:
    description: Stops a given player from moving.
    usage: /freeze <player>
    permission: leastprivilegemanagement.admin
  release:
    description: Allows a frozen player to move once again.
    usage: /release <player>
    permission: leastprivilegemanagement.admin
    aliases: [ unfreeze ]
  yell:
    description: Puts big red message on players screen.
    usage: /yell <player> <message>
    permission: leastprivilegemanagement.admin
    aliases: [ y ]